### ISSUE TITLE
Konfiguracja zaufane opinie 

### ISSUE THREAD

**Issue by Justyna130987** [ceneo/ceneo-integration#1]
Dzień dobry , 
Chciałam by skonfigurować zufane opinie według podanej uniwersalnej instrukcji. Jednak nie do końca jest jasne gdzie mam podany przez was skrypt zamieścić . Proszę o wskazówki.

![skrypt ceneo](https://user-images.githubusercontent.com/131258176/233051957-883fe8bf-f459-4496-9cd9-5ea9f33f16c8.png)

**Comment by ceneo** [comment]
Dziękujemy za informację. Problem udało rozwiązać się indywidualnie.
Przypominamy, że w razie dodatkowych pytań czy potrzeby dodatkowego wsparcia, nasza instrukcja jest dostępna pod adresem: [https://www.ceneo.pl/poradniki/instrukcja-zaufane-opinie](https://www.ceneo.pl/poradniki/instrukcja-zaufane-opinie), znajdziecie tam także sekcję najczęściej poruszanych pytań i odpowiedzi.
