### ISSUE TITLE
Opinie ceneo nie funkcjonują na sklepie soteshop

### ISSUE THREAD

**Issue by SklepTenisa** [ceneo/ceneo-integration#2]
Dzień dobry,
kontaktowałem się z obsługą klienta przez platformę ceneo, tak naprawdę od miesiąca nikt nie potrafi mi pomóc i czuje się zbywany. 
Posiadam sklep internetowy na oprogramowaniu soteshop -> na początku opinie ceneo funkcjonowały poprawnie, jednak nagle ( z niewiadomych mi przyczyn) przestały się wysyłać prośby do klientów o wydanie opinii. Konfiguracja z instrukcją dla soteshop została wykonana poprawnie ( nie ma tam wielkiej filozofii, wystarczy kod wkleić), jednak mimo to, opinie nie działają. Opinie, które kiedyś zostały dodane pokazują się na stronie -> www.skleptenisa.pl 
Będę wdzięczny za jakąkolwiek pomoc.

**Comment by ceneo** [comment]
Dzień dobry! Przepraszamy za wcześniejszy brak odpowiedzi w innym kanale korespondencji. Bardzo chcieliśmy pomóc na 120% i próbowaliśmy skontaktować się z platformą Sote ws. Państwa sklepu, aby wrócić z konkretną odpowiedzią a najlepiej zachęcić tego dostawcę oprogramowania do własnej inicjatywy w Państwa konkretnym przypadku. Niestety do dziś nie otrzymaliśmy odpowiedzi. 

Aktualizacja platformy Sote (autorstwa Sote) została opublikowana 9 stycznia i od tego momentu inne sklepy, które ją wdrożyły mogły się cieszyć nieprzerwanym funkcjonowaniem po przełączeniu na nowy skrypt Zaufanych Opinii. 

Prosimy o bezpośredni Państwa kontakt z Sote. Nasza diagnoza jest taka, że kod na stronie kończącej zamówienie w Państwa sklepie nie włącza się, przez co nie otrzymujemy danych o dokonanym zamówieniu - prawidłowe wywoływanie tego kodu powinna zapewnić platforma Sote.

**Comment by SklepTenisa** [comment]
Platforma SOTE rozwiązała problem. Temat do zamknięcia.
